#!/bin/bash
dir_name=$(date +%F)  # Find out how to get the date in DD_MM_YYYY format
mkdir "$dir_name" && cd "$dir_name" || exit

mkdir src

echo "Created project directory: ${dir_name}"

# Initialize a Node.js project
npm init --yes

# Install TypeScript
npm install typescript --save-dev

# Install Node.js type definitions
npm install @types/node --save

# Initialize a TypeScript configuration file
npx tsc --init

echo "Project initialized with TypeScript, Node.js type definitions and tsconfig.json."

# The following 8 lines were generated by Gemini and are WIP

# tmp=$(mktemp)
# jq '.compilerOptions.target = "ESNext" |
#     .compilerOptions.module = "commonjs" |
#     .compilerOptions.sourceMap = true |
#     .compilerOptions.outDir = "dist" |
#     .include = ["src"]' tsconfig.json > "$tmp" && mv "$tmp" tsconfig.json
